//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LodhranStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Id { get; set; }
        public System.DateTime BillTime { get; set; }
        public int Amount { get; set; }
        public bool IsPaid { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
